[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaCustom.variants]
  inherits = "ss09"

    [buildPlans.IosevkaCustom.variants.design]
    capital-q = "crossing-curly-tailed"
    capital-z = "straight-serifless-with-crossbar"
    f = "flat-hook-serifless"
    t = "flat-hook"
    w = "straight-serifless"
    z = "straight-serifless-with-crossbar"
    cyrl-em = "hanging-serifless"
    two = "curly-neck-serifless"
    three = "flat-top-serifless"
    four = "semi-open-non-crossing-serifless"
    five = "upright-arched-serifless"
    six = "open-contour"
    seven = "bend-serifless-crossbar"
    nine = "open-contour"
    at = "compact"
    percent = "rings-continuous-slash"

    [buildPlans.IosevkaCustom.variants.italic]
    digit-form = "old-style"
    capital-a = "curly-serifless"
    capital-b = "more-asymmetric-serifless"
    capital-g = "toothless-rounded-serifless-hooked"
    capital-h = "serifless"
    capital-j = "descending-serifed"
    capital-k = "curly-serifless"
    capital-l = "motion-serifed"
    capital-n = "asymmetric-serifless"
    capital-p = "closed-serifless"
    capital-q = "open-swash"
    capital-r = "curly-serifless"
    capital-u = "tailed-serifless"
    capital-v = "curly-serifless"
    capital-w = "curly-serifless"
    capital-x = "curly-serifless"
    capital-y = "curly-serifless"
    capital-z = "cursive-with-crossbar"
    a = "single-storey-tailed"
    b = "toothless-rounded-serifless"
    d = "tailed-serifless"
    e = "rounded"
    f = "flat-hook-tailed"
    g = "double-storey-open"
    h = "tailed-serifless"
    k = "diagonal-tailed-cursive-top-left-serifed"
    m = "tailed-serifless"
    n = "tailed-serifless"
    p = "eared-serifless"
    q = "diagonal-tailed-serifless"
    r = "hookless-serifless"
    t = "flat-hook"
    u = "tailed-serifless"
    v = "cursive-serifless"
    w = "cursive-serifless"
    x = "semi-chancery-curly"
    y = "cursive-serifless"
    z = "cursive"
    capital-delta = "curly"
    capital-lambda = "curly-serifless"
    lower-lambda = "tailed-turn"
    lower-tau = "tailed"
    lower-chi = "semi-chancery-curly"
    cyrl-capital-zhe = "curly"
    cyrl-zhe = "curly"
    cyrl-capital-ka = "curly-serifless"
    cyrl-ka = "curly-serifless"
    cyrl-el = "tailed"
    cyrl-em = "hanging-serifless"
    two = "curly-neck-serifless"
    three = "flat-top-serifless"
    four = "semi-open-non-crossing-serifless"
    five = "upright-arched-serifless"
    six = "open-contour"
    seven = "bend-serifless-crossbar"
    nine = "open-contour"
    percent = "rings-continuous-slash"
    lig-ltgteq = "flat"

  [buildPlans.IosevkaCustom.ligations]
  inherits = "dlig"

[buildPlans.IosevkaCustom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustom.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustom.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustom.slopes.Italic]
angle = 12
shape = "italic"
menu = "italic"
css = "italic"
